spring.application.name=pessoa

# Default: MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sistema_gestao?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# OpenAPI/Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Auth/JWT
app.jwt.secret=${JWT_SECRET:change-me-to-a-very-long-secret-please}
app.jwt.issuer=${JWT_ISSUER:sistemapedidos}
app.jwt.expires-in-seconds=${JWT_EXPIRES_IN_SECONDS:300}

# Usuario "admin" para autenticar e obter token.
app.auth.username=${AUTH_USERNAME:admin}
app.auth.password=${AUTH_PASSWORD:admin}
app.auth.password-bcrypt=${AUTH_PASSWORD_BCRYPT:}
